[build-system]
requires = ['setuptools', 'wheel']

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.coverage.html]
directory = 'test-reports'

[tool.coverage.run]
branch = true
source = ['pyinaturalist']

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true
known_first_party = ['test']
# Things that are common enough they may as well be grouped with stdlib imports
extra_standard_library = ['dateutil', 'pytest', 'setuptools']
